token: ""

# Must be set to the guild id of the discord server
guildId: ""
# Must be set to the channel id of the server chat channel
serverChatChannel: ""

jdaEnabled: true

webhook:
  # Must be set to the webhook url of the server chat channel
  url: ""

messages:
  # <roleColor> color of role
  # <roleName> role name
  # <discordName> name of the discord user
  # <text> actual text they sent
  discordToMcMessage: "&f[&bDiscord &f┃ <roleColor><roleName> &f]&f <discordName> » &f<text>"

  # <player> player name
  # <prefix> prefix
  # <message> message
  # U can use html markdown for this
  mcToDiscordMessage: "<message>"

  # <badWord> bad word that was blocked
  chatFilter:
    blockedMessage: "<color:#F11642>&l▍ SoulNetwork &r<color:#EF5B80>The message was blocked because it contains <color:#F11642><badWord>"
