token: ""

# Must be set to the guild id of the discord server
guildId: ""
# Must be set to the channel id of the server chat channel
serverChatChannel: ""
# Must be set to the role id of the verified role
verifiedRole: ""

webhook:
  # Must be set to the webhook url of the server chat channel
  url: ""

messages:
  # <roleColor> color of role
  # <roleName> role name
  # <discordName> name of the discord user
  # <text> actual text they sent
  discordToMcMessage: "&f[&bDiscord &f┃ <roleColor><roleName> &f]&f <discordName> » &f<text>"

  # <player> player name
  # <prefix> prefix
  # <message> message
  # U can use html markdown for this
  mcToDiscordMessage: "<message>"
