token: ""

# Must be set to the guild id of the discord server
guildId: ""
# Must be set to the channel id of the server chat channel
serverChatChannel: ""
# Must be set to the role id of the verified role
verifiedRole: ""

webhook:
  # Must be set to the webhook url of the server chat channel
  url: ""

database:
  # type must be set to either MYSQL or FILE
  type: "MYSQL"
  # MYSQL settings
  jdbcString: ""

messages:
  # <roleColor> color of role
  # <roleName> role name
  # <discordName> name of the discord user
  # <text> actual text they sent
  discordToMcMessage: "&f[&bDiscord &f┃ <roleColor><roleName> &f]&f <discordName> » &f<text>"

  # <player> player name
  # <prefix> prefix
  # <message> message
  # U can use html markdown for this
  mcToDiscordMessage: "<message>"

  # message sent when a player links their account, use \n for new line
  linkCodeMessage: "<color:#F11642>ꜱᴏᴜʟᴢꜱᴛᴇᴀʟ &8» <color:#FFA2B9>Your linking code is <color:#F11642><code><color:#FFA2B9> click me to copy and go to the channel <color:#F11642>#link-here&f!"

  # <player> player name, use \n for new line
  linkedBroadcast: "<color:#F11642>ꜱᴏᴜʟᴢꜱᴛᴇᴀʟ &8» <color:#F11642><player> <color:#FFA2B9>has successfully linked to discord! <color:#F11642>&o(/link)"

  # error message when a player tries to link their account, but they are already linked
  linkedError: "<color:#F11642>ꜱᴏᴜʟᴢꜱᴛᴇᴀʟ &8» <color:#FFA2B9>You are already linked to discord!"

  linkCodeExpired: "<color:#F11642>ꜱᴏᴜʟᴢꜱᴛᴇᴀʟ &8» <color:#FFA2B9>Your linking code has expired! Please use /link to get a new one!"