name: SoulzStealLinking
version: '1.0'
main: me.thatonedevil.soulzStealLinking.SoulzStealLinking
api-version: '1.21'
authors: [ ThatOneDevil ]
website: https://thatonedevil.github.io/

commands:
  configReload:
    description: reload config
    permission: linking.configreload